server:
  port: 8081
spring:
  datasource:
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3306/takeaway_wx_mp?useSSL=false&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 50
      # 获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 102400000
      max-file-size: 10MB
  redis:
    host: localhost
    port: 6379
    timeout: 10
    jedis:
      pool:
        max-idle: 500
        max-active: 1000
        max-wait: 500
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.cins.hobo.takeaway_wx_mp.entry
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true


jwt:
  secret: "shishangkuaike"
  expiration: 1296000
  tokenStart: "Bearer"
  tokenName: "Authorization"
  defaultPassword: "123456"

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: 食尚快客
  application-version: 1.0
  application-description: 食尚快客swagger接口调试
  try-host: http://localhost:${server.port}

#服务器文件上传文件夹
file:
  dish_pic: "/Users/hobo/Documents/食尚快客/upload_test/dishes/"

#微信相关
wx:
  mp:
    config:
      appId: "wx978128409ccb73e0"
      secret: "27c8ace46a0b86b5a9ff604c71f4bfa2"
      token: "sskk"
      aesKey: "****"
      mch_id: "商户号"
      mch_key: "商户秘钥"
      key_path: ""
      notify_url: "回调地址"

      template_id:
